---
title: "Descriptive statistics"
author: "Eric Anku and Henry Ofori-Duah"
format: html
---

```{r load-packages, message=FALSE, warning=FALSE}
# Load packages
pacman::p_load(
  rio, # Import and export dataset
  gtsummary, # Descriptive tables
  survey, # Manipulating survey dataset
  skimr, # Summary statistics
  ggstatsplot, # EDA
  ggplot2, # Visualisation
  tableone # Create table one
)
```


```{r survey-object}
# Survey object
des <- svydesign(ids=~primary_sampling_unit, strata=~stratum, weights=~child_under_five_sample_weight, data = df_clean, nest=T)
summary(des)
```
```{r proportion-nutritional-indicators}
# Proportion of nutritional indicators
svymean(~wasting, des) # Wasting
svymean(~stunting, des) # Stunting
svymean(~underweight, des) # Underweight
```
```{r regional-burden-undernutrition}
# Regional burden of undernutrition

## Wasting
reg_est_wasting <-svyby(~wasting, ~region, FUN = svymean, na.rm=T, design =des)

## Stunting
reg_est_stunting <-svyby(~stunting, ~region, FUN = svymean, na.rm=T, design =des)

## Underweight
reg_est_underweight <-svyby(~underweight, ~region, FUN = svymean, na.rm=T, design =des)

## Print output
reg_est_wasting # Wasting
reg_est_stunting # Stunting
reg_est_underweight # Underweight
```

```{r variables-by-wasting}
# Categorical variables by wasting outcome
prop.table(cat<-svytable(~sex + wasting, design = des), margin = 2)*100
prop.table(cat<-svytable(~region + wasting, design = des),margin = 2)*100
prop.table(cat<-svytable(~area + wasting,design=des), margin = 2)*100
prop.table(cat<-svytable(~child_ill_cough_two_weeks + wasting,design = des), margin = 2)*100
prop.table(cat<-svytable(~child_ill_fever_two_weeks + wasting,design = des),margin = 2)*100
prop.table(cat<-svytable(~health_insurance + wasting, design = des), margin = 2)*100
prop.table(cat<-svytable(~child_had_diarrhoea_last_two_weeks + wasting, design = des), margin = 2)*100
prop.table(cat<-svytable(~mother_educational_level + wasting,design=des), margin = 2)*100
prop.table(cat<-svytable(~ethnicity + wasting,design=des), margin = 2)*100
```

```{r  variables-by-stunting}
# Categorical variables by stunting outcome
prop.table(cat<-svytable(~sex + stunting, design = des), margin = 2)*100
prop.table(cat<-svytable(~region + stunting, design = des),margin = 2)*100
prop.table(cat<-svytable(~area + stunting,design=des), margin = 2)*100
prop.table(cat<-svytable(~child_ill_cough_two_weeks + stunting,design = des), margin = 2)*100
prop.table(cat<-svytable(~child_ill_fever_two_weeks + stunting,design = des),margin = 2)*100
prop.table(cat<-svytable(~health_insurance + stunting, design = des), margin = 2)*100
prop.table(cat<-svytable(~child_had_diarrhoea_last_two_weeks + stunting, design = des), margin = 2)*100
prop.table(cat<-svytable(~mother_educational_level + stunting,design=des), margin = 2)*100
prop.table(cat<-svytable(~ethnicity + stunting,design=des), margin = 2)*100
```

```{r variables-with-underweight}
# Categorical variables by underweight outcome
prop.table(cat<-svytable(~sex + underweight, design = des), margin = 2)*100
prop.table(cat<-svytable(~region + underweight, design = des),margin = 2)*100
prop.table(cat<-svytable(~area + underweight,design=des), margin = 2)*100
prop.table(cat<-svytable(~child_ill_cough_two_weeks + underweight,design = des), margin = 2)*100
prop.table(cat<-svytable(~child_ill_fever_two_weeks + underweight,design = des),margin = 2)*100
prop.table(cat<-svytable(~health_insurance + underweight, design = des), margin = 2)*100
prop.table(cat<-svytable(~child_had_diarrhoea_last_two_weeks + underweight, design = des), margin = 2)*100
prop.table(cat<-svytable(~mother_educational_level + underweight,design=des), margin = 2)*100
prop.table(cat<-svytable(~ethnicity + underweight,design=des), margin = 2)*100
```

```{r table-with-survey-object}
# creating tables with "svyCreateTableOne" and the survey design object "des" previously created from the survey package 

## Wasting
tab1 <- svyCreateTableOne(vars = c(
  "age_days",
  "sex",
  "region", 
  "area",
  "child_lenhei_cm", 
  "child_weight_kg",
  "child_ill_cough_two_weeks",
  "child_ill_fever_two_weeks",
  "child_had_diarrhoea_last_two_weeks",
  "health_insurance",
  "mother_educational_level",
  "ethnicity", 
  "combined_wealth_score"),
                          strata = "wasting",
  data = des, 
  addOverall = TRUE)

print(tab1, showAllLevels = TRUE)

tab1P <- print(tab1,showAllLevels = TRUE)

write.csv(tab1P, file = "data/tab1.csv")
```

```{r table-one-stunting}
## Stunting
tab2 <- svyCreateTableOne(vars = c(
  "age_days",
  "sex",
  "region", 
  "area",
  "child_lenhei_cm", 
  "child_weight_kg",
  "child_ill_cough_two_weeks",
  "child_ill_fever_two_weeks",
  "child_had_diarrhoea_last_two_weeks",
  "health_insurance",
  "mother_educational_level",
  "ethnicity", 
  "combined_wealth_score"),
                          strata = "stunting",
  data = des, 
  addOverall = TRUE)

print(tab2, showAllLevels = TRUE)

tab2P <- print(tab2,showAllLevels = TRUE)

write.csv(tab2P, file = "data/tab2.csv")
```

